//! wasm32 entry point — compiled only when `target_arch = "wasm32"`.
//!
//! # Architecture
//!
//! `mount(canvas_id)` is the single JS-callable export.  It:
//! 1. Resolves the HTML `<canvas>` element by ID.
//! 2. Starts an `eframe::WebRunner` on the canvas, running [`WasmApp`].
//! 3. Returns a [`JsWebHandle`] that JS can use to stop, resize, or inject
//!    synthetic events into the app.
//!
//! ## WebRunner integration
//!
//! The entry point is `async` to satisfy `eframe::WebRunner::start()`.  The
//! JS glue (generated by `wasm-pack`) turns the returned `Promise` into an
//! `await`-able call:
//!
//! ```js
//! const handle = await oxiui_web.mount("my-canvas");
//! ```
//!
//! ## egui Context sharing
//!
//! [`WasmApp`] captures the `egui::Context` on its first `ui()` call and
//! stores it in an `Arc<Mutex<Option<egui::Context>>>` shared with the
//! [`WebHandle`].  This lets `resize()` and `inject_event()` reach into the
//! live event loop from outside.

use std::sync::{Arc, Mutex};

use wasm_bindgen::prelude::*;
use web_sys::HtmlCanvasElement;

use crate::{JsWebHandle, MountError, WebHandle};

// ── WasmApp — minimal eframe::App bridge ──────────────────────────────────────

/// Minimal [`eframe::App`] that runs inside the browser via [`eframe::WebRunner`].
///
/// On the first `ui()` call the egui context is captured into `ctx_slot` so
/// that the companion [`WebHandle`] can call `request_repaint()` and inject
/// synthetic events.
struct WasmApp {
    /// Shared slot written once with the egui context from the first `ui` call.
    ctx_slot: Arc<Mutex<Option<egui::Context>>>,
}

impl WasmApp {
    fn new(ctx_slot: Arc<Mutex<Option<egui::Context>>>) -> Self {
        Self { ctx_slot }
    }
}

impl eframe::App for WasmApp {
    fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
        // Capture the egui context on first call; subsequent calls are no-ops.
        {
            let ctx = ui.ctx().clone();
            if let Ok(mut slot) = self.ctx_slot.lock() {
                if slot.is_none() {
                    *slot = Some(ctx);
                }
            }
        }

        // Minimal content: a centred OxiUI identity label.
        egui::CentralPanel::default().show_inside(ui, |panel_ui| {
            panel_ui.centered_and_justified(|cj| {
                cj.label("OxiUI WASM");
            });
        });
    }
}

// ── mount ─────────────────────────────────────────────────────────────────────

/// Mount an OxiUI app on the `<canvas>` element with the given DOM `id`.
///
/// Call from JavaScript after the wasm module is initialised:
/// ```js
/// const handle = await oxiui_web.mount("my-canvas");
/// ```
///
/// The function is `async` because `eframe::WebRunner::start()` is async.
///
/// # Errors
///
/// Returns a [`JsValue`] error string if:
/// - `window` is not available (worker context).
/// - `document` is not available.
/// - No element with `canvas_id` exists in the DOM.
/// - The element exists but is not an `<canvas>`.
/// - eframe / wgpu initialisation fails.
#[wasm_bindgen]
pub async fn mount(canvas_id: &str) -> Result<JsWebHandle, JsValue> {
    let window = web_sys::window()
        .ok_or_else(|| JsValue::from_str("oxiui-web: no window object — is this a browser?"))?;

    let document = window
        .document()
        .ok_or_else(|| JsValue::from_str("oxiui-web: no document on window"))?;

    let canvas: HtmlCanvasElement = document
        .get_element_by_id(canvas_id)
        .ok_or_else(|| MountError::CanvasNotFound.into())
        .and_then(|el| {
            el.dyn_into::<HtmlCanvasElement>().map_err(|_| {
                JsValue::from_str(&format!(
                    "oxiui-web: element '{canvas_id}' is not a <canvas>"
                ))
            })
        })?;

    // Shared context slot — written by WasmApp on its first paint.
    let ctx_slot: Arc<Mutex<Option<egui::Context>>> = Arc::new(Mutex::new(None));
    let ctx_slot_for_app = Arc::clone(&ctx_slot);

    let web_options = eframe::WebOptions::default();

    let app_creator: eframe::AppCreator<'static> =
        Box::new(move |_cc| Ok(Box::new(WasmApp::new(ctx_slot_for_app)) as Box<dyn eframe::App>));

    eframe::WebRunner::new()
        .start(canvas, web_options, app_creator)
        .await
        .map_err(|e| JsValue::from_str(&format!("oxiui-web: eframe init failed: {e:?}")))?;

    Ok(JsWebHandle {
        inner: WebHandle::new_wasm(ctx_slot),
    })
}

#[cfg(test)]
mod tests {
    // wasm-specific tests are best run via `wasm-pack test --headless`.
    // Unit tests that don't touch the DOM can be placed here; DOM tests
    // belong in a browser-CI pipeline.
}
